repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.3
  hooks:
    # Run the linter
    - id: ruff
      args: [ "--fix", "--line-length", "120"]
    # Run linting for docstrings
    - id:  ruff
      args: [ "--fix", "--config", "lint.select = ['D']", "--config", "lint.pydocstyle.convention = 'google'", "--exclude", "tests/*,docs/*"]
    # Run formatter
    - id: ruff-format
      args: [ "--line-length", "120" ]
