name: pre-commit

env:
  python_version: 3.12.4

on:
  pull_request:
    branches:
      - dev
      - main
  push:
    branches:
      - dev
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python_version }}
      - name: Run pre-commit hooks
        run: |
          python -m pip install --upgrade pip
          python -m pip install pre-commit
          pre-commit install
          pre-commit run --all-files
